### ISSUE TITLE
Pensando driver in Kernel

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tinkie#20]
I was having a chat with @mmlb about the kernel drivers Equinix Metal relays on, Pensando is one of them to interact with Smart NICs.

@thebsdbox pointed out that something should be already available https://github.com/linuxkit/linuxkit/blob/4cdf6bc56dd43227d5601218eaccf53479c765b9/kernel/config-5.6.x-x86_64#L2180

---

General information LinuxKit offers a pre-compiled Kernel and a workflow to load kernel modules, or to build your own kernel or modules. Here the documentation about how to do it https://github.com/linuxkit/linuxkit/blob/4cdf6bc56dd43227d5601218eaccf53479c765b9/docs/kernels.md

**Comment by mmlb** [comment]
Hmm we do IONIC in osie for the pensando nic, https://github.com/tinkerbell/osie/blob/master/installer/alpine/Dockerfile#L72 because of https://github.com/torvalds/linux/blob/master/drivers/net/ethernet/pensando/Kconfig#L20

**Comment by thebsdbox** [comment]
We can enable all of this, we're adding Realtek nics for NUCs/Brix and other devices along with Kexec.

**Comment by thebsdbox** [comment]
Our tinkie kernel -> 

https://github.com/gianarb/tinkie/blob/5585e18bfbc62a059fd8a06433b185d471e44a28/kernel/config-5.10.x-x86_64#L2209

Has pensando and ionic built in.

**Comment by thebsdbox** [comment]
Can this be closed? cc/ @mmlb @gianarb

**Comment by mmlb** [comment]
@thebsdbox we need CONFIG_IONIC=y too

**Comment by gianarb** [comment]
It is already there @mmlb 

https://github.com/gianarb/tinkie/blob/cb1336fcb12243daba4c1658e89926a244b702a3/kernel/config-5.10.x-x86_64#L2212

**Comment by mmlb** [comment]
2x :+1:
